### ISSUE TITLE
how to run this piepline in allofus workbench?

### ISSUE THREAD

**Issue by jqian2015** [TARGENE/targene-pipeline#196]
hi there, 

I am a ALLOFUS user, was trying to run this pipeline in the workbench. i created my own config file, like this, 

%%writefile allofus_test.config

workDir = "gs://fc-secure-203a5a33-ae3c-4e82-97e2-f8593d961a0f/workflows/nextflow-scratch"

params {
    STUDY_DESIGN = "ALLELE_INDEPENDENT" 
    ESTIMANDS_FILE = "gs://fc-secure-203a5a33-ae3c-4e82-97e2-f8593d961a0f/data/test/assets/interactions_allele_independent.yaml"
    COHORT = "UKBB"
    TRAITS_DATASET = "gs://fc-secure-203a5a33-ae3c-4e82-97e2-f8593d961a0f/data/test/assets/dataset.csv"
    QC_FILE = "gs://fc-secure-203a5a33-ae3c-4e82-97e2-f8593d961a0f/data/test/assets/qc_file.csv"
    LD_BLOCKS = "gs://fc-secure-203a5a33-ae3c-4e82-97e2-f8593d961a0f/data/test/assets/ld_blocks.txt"
    UKB_WITHDRAWAL_LIST = "gs://fc-secure-203a5a33-ae3c-4e82-97e2-f8593d961a0f/data/test/assets/withdrawal_list.txt"
    UKB_CONFIG = "gs://fc-secure-203a5a33-ae3c-4e82-97e2-f8593d961a0f/data/test/assets/ukbconfig_small.yaml"
    BED_FILES = "gs://fc-secure-203a5a33-ae3c-4e82-97e2-f8593d961a0f/data/test/assets/unphased_bed/ukb_chr{1,2,3}.{bed,bim,fam}"
    BGEN_FILES = "gs://fc-secure-203a5a33-ae3c-4e82-97e2-f8593d961a0f/data/test/assets/unphased_bgen/ukb_chr{1,2,3}.{bgen,bgen.bgi,sample}"
    ESTIMATOR_FILE = "gs://fc-secure-203a5a33-ae3c-4e82-97e2-f8593d961a0f/data/test/assets/estimator.jl"
}

google {
  project = "terra-vpc-sc-9be9892053bc"
  lifeSciences {
    serviceAccountEmail = "pet-11636246660618192148712505@terra-vpc-sc-9be9892053bc.iam.gserviceaccount.com"
    bootDiskSize = "20.GB"
  }
}

and then run this , 

!nextflow run https://github.com/TARGENE/targene-pipeline.git -r c292b15 -c allofus_test.config -profile allofus

had an error like this, 

Error executing process > 'TARGENE:ExtractTraits:TraitsFromUKB'

Caused by:
  Failed to submit task with name: TARGENE:ExtractTraits:TraitsFromUKB

Command executed:

  TEMPD=$(mktemp -d)
  JULIA_DEPOT_PATH=$TEMPD:/opt julia --project=/UKBMain.jl --startup-file=no --threads 10 /UKBMain.jl/scripts/process_main_dataset.jl         dataset.csv --conf ukbconfig_small.yaml --withdrawal-list withdrawal_list.txt

Command exit status:
  -

Command output:
  (empty)

so my guess is that I didn't setup config file or profiel correctly, i was also confused by these config files, at the allofus branch, there is nextflow.config in the your root directory, allofus_test.config as well, and conf/allofus.config , so would you mind telling me how exactly to run this pipeline with correct config files in allofus workbench? thanks a lot for your time and help.  

Jun

**Comment by olivierlabayle** [comment]
Hi Jun,

Thank you for your interest in using TarGene, it's great to get feedback so we can improve.

One thing in your config file is that you have COHORT = "UKBB", which is for the UK Biobank, not for AllOfUs. We don't have direct support for AllOfUs yet, @roskamsh is working on it on the `allofus` branch as you noticed but I don't know what is the status of this. The alternative is to use the COHORT = "CUSTOM", if your dataset is already a csv file containing the traits of interest and the SAMPLE_ID column to merge with genotypes later on in the pipeline.

This is roughly exlained i nthe [docs](https://targene.github.io/targene-pipeline/stable/targene/data_sources/#Custom-Dataset).

Hope that helps,
Best wishes,
Olivier

**Comment by roskamsh** [comment]
Hi @jqian2015,

Yes, this is currently being developed on the allofus branch, but is not ready for use yet. Once this has been finalized, it will be added to the docs and merged to main. 

I have this same error when I run it at the moment, and am currently communicating with the All of Us support to work out the correct way to set up the configuration in order to properly run this on All of Us. 

However in the meantime, I can give you some clarification on the different files:
1. nextflow.config file specifies nextflow parameters that do not change across any profiles or runs of the pipeline
2. allofus_test.config was a configuration I created to set up a test run of downsampled UKBB data, which is contained within the `test/` directory within this repository. This is the configuration file that a user would customize based on exactly what type of run they are executing (example: STUDY_DESIGN, ESTIMATOR_FILE), as well as where the input data is (ex: BGEN_FILES, ESTIMANDS_FILE).
3. the conf/allofus.config specifies nextflow configurations specific to executing this nextflow pipeline on the All of Us RW platform. This is still currently in development. But the idea is that this would not change based on the analysis you are running, given that it is on the All of Us RW platform. This is what the -profile allofus implements. 

I can keep you updated on this thread with progress with All of Us support regarding this.

**Comment by jqian2015** [comment]
ok, now I see it and know what is happening, if Breeshey Roskams-Hieter is the same person @roskamsh. please reach out to us so we can talk more about this.

**Comment by roskamsh** [comment]
@jqian2015 Yes this is Breeshey Roskams-Hieter! I was the one who originally submitted the help request with the AOU support team. What is the best way to reach out to you directly to discuss further?

**Comment by jqian2015** [comment]
Sam will contact you and Sjoerd. we will talk soon. also i would highly recommend you being an AOU user so you can test yourself otherwise it is hard to see the unique feature of aou platform.
